// Monster data untuk battle system
const monstersData = {
    // Tier 1 (Level 1-10)
    goblin: {
        name: 'Goblin',
        level: 1,
        hp: 20,
        maxHP: 20,
        mp: 5,
        maxMP: 5,
        atk: 8,
        matk: 3,
        def: 2,
        mdef: 1,
        hit: 60,
        flee: 40,
        exp: 50,
        gold: 30,
        element: 'none',
        rarity: 'common'
    },
    rat: {
        name: 'Rat',
        level: 1,
        hp: 15,
        maxHP: 15,
        mp: 3,
        maxMP: 3,
        atk: 6,
        matk: 2,
        def: 1,
        mdef: 0,
        hit: 55,
        flee: 35,
        exp: 40,
        gold: 20,
        element: 'none',
        rarity: 'common'
    },
    slime: {
        name: 'Slime',
        level: 2,
        hp: 25,
        maxHP: 25,
        mp: 8,
        maxMP: 8,
        atk: 7,
        matk: 5,
        def: 1,
        mdef: 2,
        hit: 50,
        flee: 30,
        exp: 60,
        gold: 40,
        element: 'water',
        rarity: 'common'
    },
    bat: {
        name: 'Bat',
        level: 2,
        hp: 18,
        maxHP: 18,
        mp: 6,
        maxMP: 6,
        atk: 9,
        matk: 3,
        def: 1,
        mdef: 1,
        hit: 65,
        flee: 50,
        exp: 55,
        gold: 35,
        element: 'none',
        rarity: 'common'
    },
    spider: {
        name: 'Spider',
        level: 3,
        hp: 30,
        maxHP: 30,
        mp: 4,
        maxMP: 4,
        atk: 11,
        matk: 2,
        def: 2,
        mdef: 1,
        hit: 70,
        flee: 45,
        exp: 75,
        gold: 50,
        element: 'none',
        rarity: 'common'
    },
    
    // Tier 2 (Level 5-15)
    zombie: {
        name: 'Zombie',
        level: 5,
        hp: 45,
        maxHP: 45,
        mp: 5,
        maxMP: 5,
        atk: 14,
        matk: 5,
        def: 4,
        mdef: 2,
        hit: 55,
        flee: 25,
        exp: 120,
        gold: 80,
        element: 'dark',
        rarity: 'uncommon'
    },
    skeleton: {
        name: 'Skeleton',
        level: 6,
        hp: 40,
        maxHP: 40,
        mp: 8,
        maxMP: 8,
        atk: 13,
        matk: 7,
        def: 3,
        mdef: 3,
        hit: 65,
        flee: 30,
        exp: 130,
        gold: 90,
        element: 'dark',
        rarity: 'uncommon'
    },
    mushroom: {
        name: 'Mushroom',
        level: 4,
        hp: 35,
        maxHP: 35,
        mp: 12,
        maxMP: 12,
        atk: 8,
        matk: 10,
        def: 2,
        mdef: 4,
        hit: 50,
        flee: 35,
        exp: 100,
        gold: 60,
        element: 'poison',
        rarity: 'uncommon'
    },
    wolf: {
        name: 'Wolf',
        level: 7,
        hp: 50,
        maxHP: 50,
        mp: 5,
        maxMP: 5,
        atk: 16,
        matk: 4,
        def: 3,
        mdef: 2,
        hit: 75,
        flee: 55,
        exp: 150,
        gold: 100,
        element: 'none',
        rarity: 'uncommon'
    },
    scorpion: {
        name: 'Scorpion',
        level: 8,
        hp: 48,
        maxHP: 48,
        mp: 6,
        maxMP: 6,
        atk: 15,
        matk: 6,
        def: 4,
        mdef: 3,
        hit: 70,
        flee: 40,
        exp: 160,
        gold: 110,
        element: 'poison',
        rarity: 'uncommon'
    },

    // Tier 3 (Level 10-20)
    orc_warrior: {
        name: 'Orc Warrior',
        level: 10,
        hp: 70,
        maxHP: 70,
        mp: 8,
        maxMP: 8,
        atk: 20,
        matk: 7,
        def: 6,
        mdef: 3,
        hit: 75,
        flee: 35,
        exp: 250,
        gold: 180,
        element: 'none',
        rarity: 'rare'
    },
    troll: {
        name: 'Troll',
        level: 12,
        hp: 90,
        maxHP: 90,
        mp: 10,
        maxMP: 10,
        atk: 22,
        matk: 8,
        def: 8,
        mdef: 4,
        hit: 70,
        flee: 30,
        exp: 300,
        gold: 220,
        element: 'none',
        rarity: 'rare'
    },
    ghost: {
        name: 'Ghost',
        level: 9,
        hp: 55,
        maxHP: 55,
        mp: 20,
        maxMP: 20,
        atk: 12,
        matk: 15,
        def: 2,
        mdef: 6,
        hit: 65,
        flee: 50,
        exp: 200,
        gold: 140,
        element: 'dark',
        rarity: 'rare'
    },
    demon: {
        name: 'Demon',
        level: 11,
        hp: 75,
        maxHP: 75,
        mp: 25,
        maxMP: 25,
        atk: 18,
        matk: 18,
        def: 5,
        mdef: 7,
        hit: 70,
        flee: 40,
        exp: 280,
        gold: 200,
        element: 'dark',
        rarity: 'rare'
    },
    dragon_whelp: {
        name: 'Dragon Whelp',
        level: 15,
        hp: 120,
        maxHP: 120,
        mp: 30,
        maxMP: 30,
        atk: 28,
        matk: 20,
        def: 10,
        mdef: 8,
        hit: 80,
        flee: 45,
        exp: 400,
        gold: 300,
        element: 'fire',
        rarity: 'rare'
    },

    // Tier 4 (Level 15-25)
    giant_spider: {
        name: 'Giant Spider',
        level: 14,
        hp: 100,
        maxHP: 100,
        mp: 8,
        maxMP: 8,
        atk: 25,
        matk: 6,
        def: 7,
        mdef: 3,
        hit: 75,
        flee: 40,
        exp: 350,
        gold: 250,
        element: 'poison',
        rarity: 'epic'
    },
    lich: {
        name: 'Lich',
        level: 18,
        hp: 95,
        maxHP: 95,
        mp: 50,
        maxMP: 50,
        atk: 15,
        matk: 30,
        def: 6,
        mdef: 12,
        hit: 70,
        flee: 50,
        exp: 450,
        gold: 350,
        element: 'dark',
        rarity: 'epic'
    },
    werewolf: {
        name: 'Werewolf',
        level: 16,
        hp: 110,
        maxHP: 110,
        mp: 12,
        maxMP: 12,
        atk: 28,
        matk: 8,
        def: 8,
        mdef: 4,
        hit: 85,
        flee: 60,
        exp: 400,
        gold: 300,
        element: 'none',
        rarity: 'epic'
    },
    wyvern: {
        name: 'Wyvern',
        level: 20,
        hp: 140,
        maxHP: 140,
        mp: 35,
        maxMP: 35,
        atk: 32,
        matk: 22,
        def: 12,
        mdef: 9,
        hit: 85,
        flee: 55,
        exp: 550,
        gold: 400,
        element: 'wind',
        rarity: 'epic'
    },
    basilisk: {
        name: 'Basilisk',
        level: 17,
        hp: 115,
        maxHP: 115,
        mp: 15,
        maxMP: 15,
        atk: 26,
        matk: 12,
        def: 10,
        mdef: 7,
        hit: 80,
        flee: 45,
        exp: 420,
        gold: 320,
        element: 'poison',
        rarity: 'epic'
    },

    // Tier 5 (Level 20+)
    dark_lord: {
        name: 'Dark Lord',
        level: 25,
        hp: 200,
        maxHP: 200,
        mp: 80,
        maxMP: 80,
        atk: 40,
        matk: 35,
        def: 15,
        mdef: 15,
        hit: 90,
        flee: 60,
        exp: 800,
        gold: 600,
        element: 'dark',
        rarity: 'legendary'
    },
    ancient_dragon: {
        name: 'Ancient Dragon',
        level: 30,
        hp: 250,
        maxHP: 250,
        mp: 100,
        maxMP: 100,
        atk: 50,
        matk: 45,
        def: 20,
        mdef: 18,
        hit: 95,
        flee: 70,
        exp: 1000,
        gold: 800,
        element: 'fire',
        rarity: 'legendary'
    },
    fallen_angel: {
        name: 'Fallen Angel',
        level: 22,
        hp: 170,
        maxHP: 170,
        mp: 70,
        maxMP: 70,
        atk: 35,
        matk: 38,
        def: 12,
        mdef: 14,
        hit: 85,
        flee: 65,
        exp: 700,
        gold: 550,
        element: 'dark',
        rarity: 'legendary'
    }
};

module.exports = monstersData;
